version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    networks:
      testing_net:
        ipv4_address: 172.1.1.1
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.1.1.2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      testing_net:
        ipv4_address: 172.1.1.2
  mongo:
    image: mongo:latest
    ports:
        - "27017:27017"
    networks:
      testing_net:
        ipv4_address: 172.1.1.3
  exam-client:
    image: exam-client
    ports:
      - "8080:8080"
    networks:
      testing_net:
        ipv4_address: 172.1.1.10
  exam-server:
    image: exam-server
    ports:
      - "8081:8081"
    networks:
      testing_net:
        ipv4_address: 172.1.1.11
  exam-worker:
    image: exam-worker
    ports:
      - "8082:8082"
    links:
      - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    depends_on:
      - mongo
    networks:
      testing_net:
        ipv4_address: 172.1.1.12
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.1.0.0/16
