server:
  port: 8082
spring:
  application:
    name: WorkerApplication
  kafka:
    bootstrap-servers: kafka:9092
    group-id: myGroup1
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: 'com.example.worker.entity.RequestData'
            type:
              mapping: 'com.example.server.entity.RequestData:com.example.worker.entity.RequestData'
            trusted:
              packages: 'com.example.server.entity'
        partition:
          assignment:
            strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
  data:
    mongodb:
      host: mongo
      port: 27017
